const CARDS = [
  // Pregnancy
  { es: "El embarazo", nl: "Zwangerschap", category: "Pregnancy" },
  { es: "Embarazada", nl: "Zwanger", category: "Pregnancy" },
  { es: "El bebé", nl: "Baby", category: "Pregnancy" },
  { es: "El feto", nl: "Foetus", category: "Pregnancy" },
  { es: "El útero", nl: "Baarmoeder", category: "Pregnancy" },
  { es: "La placenta", nl: "Placenta", category: "Pregnancy" },
  { es: "El trimestre", nl: "Trimester", category: "Pregnancy" },
  { es: "La ecografía", nl: "Echo / echografie", category: "Pregnancy" },
  { es: "Las náuseas", nl: "Misselijkheid / ochtendmisselijkheid", category: "Pregnancy" },
  { es: "El antojo", nl: "Zwangerschapshonger", category: "Pregnancy" },
  { es: "Los movimientos fetales", nl: "Foetale bewegingen", category: "Pregnancy" },
  { es: "La comadrona", nl: "Verloskundige", category: "Pregnancy" },
  { es: "El ginecólogo", nl: "Gynaecoloog", category: "Pregnancy" },
  { es: "La cesárea", nl: "Keizersnede", category: "Pregnancy" },
  { es: "El parto natural", nl: "Natuurlijke bevalling", category: "Pregnancy" },
  { es: "Las contracciones", nl: "Weeën", category: "Pregnancy" },
  { es: "Dilatar", nl: "Ontsluiten", category: "Pregnancy" },
  { es: "Romper aguas", nl: "Vliezen breken", category: "Pregnancy" },
  { es: "Empujar", nl: "Persen", category: "Pregnancy" },
  { es: "El cordón umbilical", nl: "Navelstreng", category: "Pregnancy" },
  { es: "El parto", nl: "Bevalling / weeën", category: "Pregnancy" },
  { es: "Dar a luz", nl: "Bevallen", category: "Pregnancy" },
  { es: "El recién nacido", nl: "Pasgeborene", category: "Pregnancy" },
  { es: "La lactancia", nl: "Borstvoeding", category: "Pregnancy" },
  { es: "Amamantar", nl: "Borstvoeding geven", category: "Pregnancy" },
  { es: "El calostro", nl: "Biest / colostrum", category: "Pregnancy" },
  { es: "La epidural", nl: "Ruggenprik / epiduraal", category: "Pregnancy" },

  // Hospital
  { es: "El hospital", nl: "Ziekenhuis", category: "Hospital" },
  { es: "La sala de partos", nl: "Verloskamer", category: "Hospital" },
  { es: "La sala de espera", nl: "Wachtkamer", category: "Hospital" },
  { es: "El médico", nl: "Arts / dokter", category: "Hospital" },
  { es: "La enfermera", nl: "Verpleegkundige", category: "Hospital" },
  { es: "El obstetra", nl: "Gynaecoloog-verloskundige", category: "Hospital" },
  { es: "El anestesiólogo", nl: "Anesthesioloog", category: "Hospital" },
  { es: "La anestesia", nl: "Verdoving / anesthesie", category: "Hospital" },
  { es: "La camilla", nl: "Brancard", category: "Hospital" },
  { es: "El gotero", nl: "Infuus", category: "Hospital" },
  { es: "La vía intravenosa", nl: "Infuuslijn", category: "Hospital" },
  { es: "El monitor fetal", nl: "Foetale monitor / CTG", category: "Hospital" },
  { es: "La sala de neonatos", nl: "Neonatale afdeling", category: "Hospital" },
  { es: "El alta", nl: "Ontslag uit het ziekenhuis", category: "Hospital" },
  { es: "Ingresar", nl: "Opgenomen worden", category: "Hospital" },
  { es: "La incubadora", nl: "Couveuse", category: "Hospital" },
  { es: "El pediatra", nl: "Kinderarts", category: "Hospital" },
  { es: "La revisión", nl: "Controle", category: "Hospital" },
  { es: "El historial médico", nl: "Medisch dossier", category: "Hospital" },
  { es: "La urgencia", nl: "Spoedeisende hulp", category: "Hospital" },

  // Raising a Child
  { es: "El niño / la niña", nl: "Jongen / meisje", category: "Parenting" },
  { es: "El bebé", nl: "Baby", category: "Parenting" },
  { es: "El pañal", nl: "Luier", category: "Parenting" },
  { es: "Cambiar el pañal", nl: "De luier verschonen", category: "Parenting" },
  { es: "La cuna", nl: "Wieg / ledikant", category: "Parenting" },
  { es: "El cochecito", nl: "Kinderwagen", category: "Parenting" },
  { es: "El portabebés", nl: "Draagzak / draagdoek", category: "Parenting" },
  { es: "La trona", nl: "Kinderstoel / eetstoel", category: "Parenting" },
  { es: "El chupete", nl: "Fopspeen", category: "Parenting" },
  { es: "El biberón", nl: "Babyfles", category: "Parenting" },
  { es: "La papilla", nl: "Babyvoeding / puree", category: "Parenting" },
  { es: "Dormir la siesta", nl: "Een dutje doen", category: "Parenting" },
  { es: "Hacer eructar", nl: "De baby laten boeren", category: "Parenting" },
  { es: "La fiebre", nl: "Koorts", category: "Parenting" },
  { es: "Vacunar", nl: "Vaccineren", category: "Parenting" },
  { es: "La vacuna", nl: "Vaccin", category: "Parenting" },
  { es: "Crecer", nl: "Groeien", category: "Parenting" },
  { es: "El gateo", nl: "Kruipen", category: "Parenting" },
  { es: "Los primeros pasos", nl: "Eerste stapjes", category: "Parenting" },
  { es: "El dentista", nl: "Tandarts", category: "Parenting" },
  { es: "El colegio", nl: "School", category: "Parenting" },
  { es: "La guardería", nl: "Kinderdagverblijf / crèche", category: "Parenting" },
  { es: "El juguete", nl: "Speelgoed", category: "Parenting" },
  { es: "El cuento", nl: "Verhaal / sprookje", category: "Parenting" },
  { es: "La baja por maternidad", nl: "Zwangerschapsverlof", category: "Parenting" },
  { es: "La baja por paternidad", nl: "Vaderschapsverlof", category: "Parenting" },
];
