const CARDS = [
  // Pregnancy
  { es: "El embarazo", en: "Pregnancy", category: "Pregnancy" },
  { es: "Embarazada", en: "Pregnant", category: "Pregnancy" },
  { es: "El bebé", en: "Baby", category: "Pregnancy" },
  { es: "El feto", en: "Fetus", category: "Pregnancy" },
  { es: "El útero", en: "Uterus / womb", category: "Pregnancy" },
  { es: "La placenta", en: "Placenta", category: "Pregnancy" },
  { es: "El trimestre", en: "Trimester", category: "Pregnancy" },
  { es: "La ecografía", en: "Ultrasound", category: "Pregnancy" },
  { es: "Las náuseas", en: "Nausea / morning sickness", category: "Pregnancy" },
  { es: "El antojo", en: "Food craving", category: "Pregnancy" },
  { es: "Los movimientos fetales", en: "Fetal movements", category: "Pregnancy" },
  { es: "La comadrona", en: "Midwife", category: "Pregnancy" },
  { es: "El ginecólogo", en: "Gynecologist", category: "Pregnancy" },
  { es: "La cesárea", en: "C-section", category: "Pregnancy" },
  { es: "El parto natural", en: "Natural birth", category: "Pregnancy" },
  { es: "Las contracciones", en: "Contractions", category: "Pregnancy" },
  { es: "Dilatar", en: "To dilate", category: "Pregnancy" },
  { es: "Romper aguas", en: "To break water", category: "Pregnancy" },
  { es: "Empujar", en: "To push", category: "Pregnancy" },
  { es: "El cordón umbilical", en: "Umbilical cord", category: "Pregnancy" },
  { es: "El parto", en: "Childbirth / labor", category: "Pregnancy" },
  { es: "Dar a luz", en: "To give birth", category: "Pregnancy" },
  { es: "El recién nacido", en: "Newborn", category: "Pregnancy" },
  { es: "La lactancia", en: "Breastfeeding", category: "Pregnancy" },
  { es: "Amamantar", en: "To breastfeed", category: "Pregnancy" },
  { es: "El calostro", en: "Colostrum", category: "Pregnancy" },
  { es: "La epidural", en: "Epidural", category: "Pregnancy" },

  // Hospital
  { es: "El hospital", en: "Hospital", category: "Hospital" },
  { es: "La sala de partos", en: "Delivery room", category: "Hospital" },
  { es: "La sala de espera", en: "Waiting room", category: "Hospital" },
  { es: "El médico", en: "Doctor", category: "Hospital" },
  { es: "La enfermera", en: "Nurse", category: "Hospital" },
  { es: "El obstetra", en: "Obstetrician", category: "Hospital" },
  { es: "El anestesiólogo", en: "Anesthesiologist", category: "Hospital" },
  { es: "La anestesia", en: "Anesthesia", category: "Hospital" },
  { es: "La camilla", en: "Stretcher / gurney", category: "Hospital" },
  { es: "El gotero", en: "IV drip", category: "Hospital" },
  { es: "La vía intravenosa", en: "IV line", category: "Hospital" },
  { es: "El monitor fetal", en: "Fetal monitor", category: "Hospital" },
  { es: "La sala de neonatos", en: "Neonatal ward", category: "Hospital" },
  { es: "El alta", en: "Discharge from hospital", category: "Hospital" },
  { es: "Ingresar", en: "To be admitted", category: "Hospital" },
  { es: "La incubadora", en: "Incubator", category: "Hospital" },
  { es: "El pediatra", en: "Pediatrician", category: "Hospital" },
  { es: "La revisión", en: "Check-up", category: "Hospital" },
  { es: "El historial médico", en: "Medical record", category: "Hospital" },
  { es: "La urgencia", en: "Emergency", category: "Hospital" },

  // Raising a Child
  { es: "El niño / la niña", en: "Boy / girl", category: "Parenting" },
  { es: "El bebé", en: "Baby", category: "Parenting" },
  { es: "El pañal", en: "Diaper / nappy", category: "Parenting" },
  { es: "Cambiar el pañal", en: "To change the diaper", category: "Parenting" },
  { es: "La cuna", en: "Crib / cot", category: "Parenting" },
  { es: "El cochecito", en: "Pram / stroller", category: "Parenting" },
  { es: "El portabebés", en: "Baby carrier", category: "Parenting" },
  { es: "La trona", en: "High chair", category: "Parenting" },
  { es: "El chupete", en: "Pacifier / dummy", category: "Parenting" },
  { es: "El biberón", en: "Baby bottle", category: "Parenting" },
  { es: "La papilla", en: "Baby food / puree", category: "Parenting" },
  { es: "Dormir la siesta", en: "To take a nap", category: "Parenting" },
  { es: "Hacer eructar", en: "To burp (the baby)", category: "Parenting" },
  { es: "La fiebre", en: "Fever", category: "Parenting" },
  { es: "Vacunar", en: "To vaccinate", category: "Parenting" },
  { es: "La vacuna", en: "Vaccine", category: "Parenting" },
  { es: "Crecer", en: "To grow", category: "Parenting" },
  { es: "El gateo", en: "Crawling", category: "Parenting" },
  { es: "Los primeros pasos", en: "First steps", category: "Parenting" },
  { es: "El dentista", en: "Dentist", category: "Parenting" },
  { es: "El colegio", en: "School", category: "Parenting" },
  { es: "La guardería", en: "Nursery / daycare", category: "Parenting" },
  { es: "El juguete", en: "Toy", category: "Parenting" },
  { es: "El cuento", en: "Story / tale", category: "Parenting" },
  { es: "La baja por maternidad", en: "Maternity leave", category: "Parenting" },
  { es: "La baja por paternidad", en: "Paternity leave", category: "Parenting" },
];
